modLoader="kotlinforforge"
loaderVersion="[1.9,)"
license='AGPLv3'

[[mods]]
modId="mesagisto"
version="${file.jarVersion}"
displayName="MesagistoMod"
authors="Itsusinn"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.mesagisto]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mesagisto]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.12.2,)"
    ordering="NONE"
    side="BOTH"
